CREATE TABLE
IF NOT EXISTS users
(
  id SERIAL PRIMARY KEY,
  first_name VARCHAR
(50) NOT NULL,
  last_name VARCHAR
(50) NOT NULL,
  phone_number VARCHAR
(15) NOT NULL UNIQUE,
  password VARCHAR
(100) NOT NULL,
  email VARCHAR
(100) NOT NULL UNIQUE,
  is_admin BOOLEAN DEFAULT false,
  created_on DATETIME DEFAULT NOW
(),
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
